### ISSUE TITLE
Nether/End Uranium Ore cannot be smelted on SMP

### ISSUE THREAD

**Issue by sandalle** [Rohzek/SimpleOreGeneration#7] opened 2017-05-11 15:42 UTC
Similar, but not identical, to https://github.com/Rohzek/SimpleOreGeneration/issues/5 , Nether and End Uranium Ore from Simple Ore Generation (3.4.1) for Industrial Craft 2 (Experimental 2.7.12-ex111 is used here) will neither smelt nor macerate (IC2 machines, nor vanilla furnace) in SMP (using modpack https://minecraft.curseforge.com/projects/nst-unofficial-exploration , which has older versions pending testing and bugfixes, and configs from https://github.com/sandalle/nst-exploration-unofficial , which are current), though JEI says it may be macerated.

These ores will macerate on SSP into dust (crushed uranium ore per IC2), but will not smelt into their Surface ore equivalent (IC2 Lead Ore). I am using UniDict to manage ore type duplication into a single ore, if that matters.

- Forge Mod Loader 1.11.2-13.20.0.2296
- Simple Ore Generation 3.4.1
- Industrial Craft 2 Experimental 2.7.12-ex111
- UniDict 1.11.2-1.0

**Comment by Rohzek** [comment] 2017-05-11 18:20
By default, I didn't add a smelting recipe for nether/end ore Uranium, as I figured since the surface version didn't smelt anyway, people wouldn't waste the fuel when it could be put straight into a macerator. I guess I can include one anyway.

It's very odd that it works as intended in SSP, but not in SMP. I'm not sure what's causing it, but it's not just you. It seems I have this problem even on the private server my girlfriend and I play together on, that doesn't have UniDict or anything similar to it. It may be IndustrialCraft not registering things from other mods correctly? What happens if you put Yellowrium in the Macerator? It's also registered as "oreUranium"

**Comment by Rohzek** [comment] 2017-05-11 19:44
It seems adding the macerator recipes myself, rather than expecting IC2 to find and register them from the ore dictionary fixed the problem? [Here's](https://github.com/Rohzek/SimpleOreGeneration/tree/master/build) an updated version of 3.4.1. As before, if this solves your problem, and doesn't create more, I'll upload the fix to CurseForge.

**Comment by sandalle** [comment] 2017-05-12 03:32
I did not test on SMP as the Minecraft authentication servers are [down for the last 196 minutes](http://xpaw.ru/mcstatus/). I'll try again later.

With the latest 3.4.1 (sha256: 6c9218d615a4f8df51d72ae49ff703588f83a4217617740a627c2cdd754b7028) , here's what I have going:

- Nether/End Copper/Tin/Lead Ore will Macerate (IC2 or Actually Additions Crusher/Double Crusher) into two crushed ores/dusts.
  - Just Enough Items (JEI) shows this recipe correctly.
- Nether/End Copper/Tin/Lead Ore will smelt (IC2 or vanilla furnace) into one Surface ore
  - JEI shows this recipe correctly.
- Nether/End Uranium Ore will Macerate (IC2) into two IC2 Crushed Uranium dusts, or crush (Actually Additions) into two Yellorium dusts.
  - JEI shows this recipe correctly.

I do have "B:smeltToIngots=false" in simpleoregen/options.cfg .

From Extreme Reactors (nee Big Reactors), the Yellorite ore just smelts one ore -> one Yellorium ingot in a Furnace and has no Macerator recipes for doubling, though the Actually Additions Crusher and Double Crusher will do one Yellorite Ore -> two Yellorium dusts, which each then smelt into one Yellorium ingot.

**Comment by Rohzek** [comment] 2017-05-12 10:30
That sounds as if everything is working as intended?

**Comment by sandalle** [comment] 2017-05-12 16:22
Yes, sorry I didn't clearly state that this is now working as intended. :) It was late when I tested and I thought of that as I was laying down to sleep, but figured I'd correct it in the morning after additional testing. ;)

The latest 3.4.1 also works on SMP, thanks!

**Comment by Rohzek** [comment] 2017-05-12 17:18
Okay, was just making sure before closing this up.
Glad everything got fixed up. :)

**Closed as completed by Rohzek** 2017-05-12 17:18 UTC
